baseURL = "https://fico-ita.github.io"
title = "FICO-ITA"
author = "FICO"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  mainSections = ['noticias']

  googleFonts = true

  [params.logo]
    main = "img/logo/ita-logo.png"
    alt = "FICO-ITA"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "FICO-ITA | Grupo de Interesse em Finanças Computacionais e Investimentos Sistemáticos"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "FICO-ITA é um grupo de pesquisa em Finanças Computacionais e Investimentos Sistemáticos multidisciplinar atuando dentro do Instituto Tecnológico de Aeronáutica"
    meta_og_title = "FICO-ITA | Grupo de Interesse em Finanças Computacionais e Investimentos Sistemáticos"
    meta_og_type = "website"
    meta_og_url = "https://fico-ita.github.io"
    #meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "FICO-ITA é um grupo de pesquisa em Finanças Computacionais e Investimentos Sistemáticos multidisciplinar atuando dentro do Instituto Tecnológico de Aeronáutica."
    #meta_twitter_card = "summary_large_image"
    #meta_twitter_site = "@username"
    #meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "FICO-ITA"
    name = "Sobre"
    url = "/fico/"
    weight = 1

  [[menu.main]]
    identifier = "fincomp"
    name = "Finanças Computacionais"
    url = "/atividades/fincomp/"
    weight = 2

  [[menu.main]]
    identifier = "estrategia"
    name = "Estratégias de Investimentos"
    url = "/atividades/estrategia/"
    weight = 3

  [[menu.main]]
    identifier = "ensino"
    name = "Ensino e Pesquisa"
    url = "/atividades/ensino/"
    weight = 4

  [[menu.main]]
    #identifier = "products"
    #name = "Atividades"
    #url = "/atividades/"
    #weight = 2

  [[menu.main]]
    #identifier = "blog"
    #name = "Notícias"
    #url = "/blog/"
    #weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contato"
    url = "/contact/"
    weight = 5

  [[menu.main]]
    #name = "Linkedin"
    #url = "https://github.com/fico-ita/fico-ita.github.io"
    #pre = "<i class='fa-brands fa-linkedin-in'></i>"
    #weight = 6

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    #name = "Github"
    #url = "https://github.com/fico-ita/fico-ita.github.io"
    #pre = "<i class='icon-github text-2xl'></i>"
    #weight = 2

  [[menu.footer]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/company/fico-ita/"
    pre = "<i class='fa-brands fa-linkedin-in'></i>"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true 