baseURL = "https://fico-ita.github.io"
title = "FICO-ITA"
author = "FICO"
languageCode = "pt"
defaultContentLanguage = "pt"
#defaultContentLanguageInSubdir: true
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[languages]
  [languages.pt]
    languageName = "Português"
    weight = 1
    
  [languages.en]
    languageName = "English"
    weight = 2

    [languages.en.params]
      [languages.en.params.site]
        name = "FICO-ITA | Computational Finance Interest Group"

[params]

  mainSections = ['news']

  googleFonts = true

  [params.logo]
    main = "/img/logo/ita-logo.png"
    alt = "FICO-ITA"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "FICO-ITA | Grupo de Interesse em Finanças Computacionais"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

[menu]

  [[menu.main]]
    identifier = "FICO-ITA"
    url = "/fico/"
    weight = 1

  [[menu.main]]
    identifier = "fincomp"
    url = "/atividades/fincomp/"
    weight = 2

  [[menu.main]]
    identifier = "estrategia"
    url = "/atividades/estrategia/"
    weight = 3

  [[menu.main]]
    identifier = "ensino"
    url = "/atividades/ensino/"
    weight = 4

  [[menu.main]]
    #identifier = "products"
    #name = "Atividades"
    #url = "/atividades/"
    #weight = 2

  [[menu.main]]
    #identifier = "blog"
    #name = "Notícias"
    #url = "/blog/"
    #weight = 3

  [[menu.main]]
    identifier = "contato"
    url = "/contact/"
    weight = 5

  [[menu.main]]
    identifier = "flag"
    name = " "
    url = "/en"
    weight = 6

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    #name = "Github"
    #url = "https://github.com/fico-ita/fico-ita.github.io"
    #pre = "<i class='icon-github text-2xl'></i>"
    #weight = 2

  [[menu.footer]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/company/fico-ita/"
    pre = "<i class='fa-brands fa-linkedin-in'></i>"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true 
